<a href="https://colab.research.google.com/github/rahulsing/pytorch_demo/blob/master/00_pytorch_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

    100% |████████████████████████████████| 91.1MB 58.7MB/s 
    100% |████████████████████████████████| 2.0MB 11.0MB/s 
fastai 1.0.42 has requirement torch>=1.0.0, but you'll have torch 0.4.1 which is incompatible.


In [2]:
import torch
print(torch.__version__ )

0.4.1


Tensors are array of multipledimentional data, they are interoperable with Numpy Arrays

Tensor form part of the computational graph of your network and record operations performed

In [4]:
tensor_array=torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [0]:
tensor_uninitialized=torch.Tensor(3,3)


In [13]:
# print total number of elements space
torch.numel(tensor_uninitialized)

9

In [16]:
# randomaly intialize with some value
tensor_initialized=torch.rand(2,3)
tensor_initialized

tensor([[0.3865, 0.6662, 0.0927],
        [0.6180, 0.7982, 0.2300]])

In [18]:
# tensor with specified data type

tensor_long=torch.LongTensor([1.0,2.0,3.0])
tensor_long

tensor([1, 2, 3])

In [19]:
tensor_byte=torch.ByteTensor([0,261,1,-5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [21]:
# intialize all tensor with one
tensor_ones=torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# intialize all tensor with one
tensor_zeros=torch.zeros(10)
tensor_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# square matix with diagonal as ones
tensor_eye=torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
# print index position of non zero in metrix
non_zero=torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [27]:
# create tenosr of like another

tensor_ones_shape_eye=torch.ones_like(tensor_eye)
tensor_ones_shape_eye


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
# inplace and out of place operations
# inplace operation: modifies the same tensor, ALL IN-PLACE OPERATIONS HAVE THE SUFFIX "_"
# out of operations: creates a new tensor


initial_tensor=torch.rand(3,3)

initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [31]:
# out of place operation, creates a new tensor
new_tensor=initial_tensor.add(4)
new_tensor 


tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [33]:
#inplace operation will change the intial tensor with 5 added to all elemets of matrix
initial_tensor.add_(5)
initial_tensor


tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

# **Working with Numpy and Tensor **

In [0]:
import numpy as np


In [35]:
numpy_arr=np.array([1,2,3])
numpy_arr

array([1, 2, 3])

In [36]:
# converting numpy array to tensor
tensor=torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3])

In [38]:
# converting numpy array from tensor
numpy_from_tensor=tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [39]:
# updating an element of numyp array
numpy_arr[1]=4
numpy_arr

array([1, 4, 3])

In [40]:
# tensor gets update on np array update
tensor

tensor([1, 4, 3])

In [41]:
# slice and dice on tensor is similar to array

inital_tensor=torch.rand(2,3)
inital_tensor

tensor([[0.9135, 0.4563, 0.2798],
        [0.8891, 0.3326, 0.1134]])

In [42]:
inital_tensor[0,2]

tensor(0.2798)

In [43]:
inital_tensor[:,1:]

tensor([[0.4563, 0.2798],
        [0.3326, 0.1134]])

In [45]:
inital_tensor.size()

torch.Size([2, 3])

In [46]:
inital_tensor.shape

torch.Size([2, 3])

In [47]:
# create view from tensor

resized_tensor=inital_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [48]:
resized_tensor

tensor([0.9135, 0.4563, 0.2798, 0.8891, 0.3326, 0.1134])

In [49]:
inital_tensor[0,2]=0.1111

# updating the main/orignal tensor , will reflect in view
resized_tensor

tensor([0.9135, 0.4563, 0.1111, 0.8891, 0.3326, 0.1134])

In [51]:
resized_tensor_new=inital_tensor.view([3,2])
resized_tensor_new.shape  

torch.Size([3, 2])

In [52]:
resized_tensor_new

tensor([[0.9135, 0.4563],
        [0.1111, 0.8891],
        [0.3326, 0.1134]])

In [53]:
# inferring the dimention from orignal torch while crate view
resized_matrix=inital_tensor.view([-1,2])
resized_matrix.shape

torch.Size([3, 2])

In [0]:
sorted_tensor, sorted_indices=torch.sort(inital_tensor)

In [59]:
sorted_tensor

tensor([[0.1111, 0.4563, 0.9135],
        [0.1134, 0.3326, 0.8891]])

In [58]:
sorted_indices

tensor([[2, 1, 0],
        [2, 1, 0]])

In [60]:
# sort the tesnor column wise by specifing dim
sorted_tensor, sorted_indices=torch.sort(inital_tensor,dim=0)
sorted_tensor

tensor([[0.8891, 0.3326, 0.1111],
        [0.9135, 0.4563, 0.1134]])