<a href="https://colab.research.google.com/github/rahulsing/pytorch_demo/blob/master/01_pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Autograd** is core package in PyTorch. This is the package which **performs automatic differentiation to calculate gradients during the training phase **of a neural network. In a neural network, you have tensors and you perform operations on them. Autograd **remembers all of the executed operations that you've performed in the forward phase of your neural network prediction, it then replays these operations in the backward phase **or the back propagation in order to calculate gradients.

In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [3]:
import torch

tensor = torch.Tensor([[3,4],[7,5]])
tensor

tensor([[3., 4.],
        [7., 5.]])

In [4]:
tensor.requires_grad

False

In [5]:
tensor.requires_grad_()

tensor([[3., 4.],
        [7., 5.]], requires_grad=True)

In [0]:
tensor.requires_grad

True

In [8]:
print(tensor.grad)

None


In [9]:
print(tensor.grad_fn)

None


In [0]:
out = tensor * tensor

In [11]:
out.requires_grad

True

In [12]:
print(out.grad_fn)

In [13]:
print(tensor.grad_fn)

None


In [0]:
out = (tensor * tensor).mean()
#print(out.grad_fn)


In [21]:
print(out.grad_fn)

In [0]:
out.backward()

In [23]:
print(tensor.grad)

tensor([[3., 4.],
        [7., 5.]])


In [24]:
new_tensor = tensor * tensor
print(new_tensor.requires_grad)

True


In [25]:
with torch.no_grad():
  new_tensor = tensor * tensor
  print('new_tensor = ',new_tensor)
  print('requires_grad for tensor = ',tensor.requires_grad)
  print('requires_grad for new_tensor = ',new_tensor.requires_grad)
   

new_tensor =  tensor([[ 9., 16.],
        [49., 25.]])
requires_grad for tensor =  True
requires_grad for new_tensor =  False
